# Generated by Django 5.2.6 on 2025-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign_application', '0002_remove_campaign_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='html_content',
            field=models.TextField(blank=True),
        ),
    ]
